language: java
jdk:
    - oraclejdk8
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install oracle-java8-installer

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
        - 0.5-branch
